/*
 * File: app/store/SamplingMethod.js
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.store.SamplingMethod', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'samplingMethod',
            data: [
                {
                    'name': 'digital filter',
                    'value': 0
                },
                {
                    'name': 'exeedance',
                    'value': 1
                },
                {
                    'name': 'resample',
                    'value': 2
                },
                {
                    'name': 'integrate',
                    'value': 3
                },
                {
                    'name': 'compare',
                    'value': 4
                },
                {
                    'name': 'subract',
                    'value': 5
                },
                {
                    'name': 'integrate',
                    'value': 6
                },
                {
                    'name': 'data values',
                    'value': 7
                },
                {
                    'name': 'Hydro events',
                    'value': 8
                },
                {
                    'name': 'hydro indicies',
                    'value': 9
                },
                {
                    'name': 'statistics',
                    'value': 10
                }
                
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'value'
                }
            ]
        }, cfg)]);
    }
});